CREATE TABLE "user" (
   id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL
);

CREATE TABLE comment (
   id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   user_comment VARCHAR(255) NOT NULL,
   date_comment TIMESTAMPTZ DEFAULT NOW(),
   user_id INT NOT NULL REFERENCES "user"(id)
);
